### ISSUE TITLE
several errors when compiling hello_world from kendryte-standalone-sdk

### ISSUE THREAD

**Issue by GitJer** [kendryte/kendryte-gnu-toolchain#4]
I have installed the kendryte-gnu-toolchain as instructed. The configure/make took a long time but finished without errors. When compiling the hello_world example in the kendryte-standalone-sdk (downloaded at the same time as the toolchain, so not an old version) I get several errors:

- can't link hard-float modules with soft-float modules
- failed to merge target specific data of file CMakeFiles/hello_world.dir/src/hello_world/main.c.obj
- undefined reference to `__floatunsidf' (and also: __divdf3, __muldf3, __fixunsdfsi, __extendsfdf2)

Searching for solutions has not yet solved these errors. Is there something I forgot to do? Or did wrong?

**Comment by vowstar** [comment]
We are sorry for bringing you inconvenience.
Please use our pre-compiled toolchain (including OSX)
https://github.com/kendryte/kendryte-gnu-toolchain/releases/tag/v8.2.0-20190213

Or recompile with the following flag

- Linux

```bash
./configure --prefix=/opt/kendryte-toolchain --with-cmodel=medany --with-arch=rv64imafc --with-abi=lp64f

make
```

- OSX

```bash
./configure --prefix=/usr/local/opt/kendryte-toolchain --with-cmodel=medany --with-arch=rv64imafc --with-abi=lp64f
make
```


This fix is ​​only for the current SDK and may change in the future.

**Comment by GitJer** [comment]
This worked! Thank you.

Note that on a machine with multiple cores the -j option for make may help speed things up.
E.g. on a 4 core CPU you can use the command "make -j 6"
