### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by onionstack** [kendryte/kendryte-gnu-toolchain#5]
/home/l/k210/kendryte-toolchain/bin/../libexec/gcc/riscv64-unknown-elf/8.2.0/cc1: error while loading shared libraries: libisl.so.19: cannot open shared object file: No such file or directory
lib/CMakeFiles/kendryte.dir/build.make:62: recipe for target 'lib/CMakeFiles/kendryte.dir/freertos/tasks.c.obj' failed
make[2]: *** [lib/CMakeFiles/kendryte.dir/freertos/tasks.c.obj] Error 1
CMakeFiles/Makefile2:122: recipe for target 'lib/CMakeFiles/kendryte.dir/all' failed
make[1]: *** [lib/CMakeFiles/kendryte.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by vowstar** [comment]
export LD_LIBRARY_PATH=/home/l/k210/kendryte-toolchain/bin:$LD_LIBRARY_PATH
Or,
Install libisl

-----------------------------
Please try static link: (make sure you have write access to /opt/kendryte-toolchain)
```bash
git clone --recursive https://github.com/kendryte/kendryte-gnu-toolchain
cd kendryte-gnu-toolchain
cd riscv-gcc
./contrib/download_prerequisites
cd ..
./configure --prefix=/opt/kendryte-toolchain --with-cmodel=medany --with-arch=rv64imafc --with-abi=lp64f
make -j8
```
